name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
      
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-11]
        include:
          - os: ubuntu-22.04
            cibw_archs: "aarch64"
            
    steps:
      - name: Set up QEMU
        if: matrix.cibw_archs == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Install dependencies
        if: matrix.os == 'macos-11'
        run: |
          brew install protobuf

      - name: Install dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt update
          sudo apt install protobuf-compiler
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
      
      - uses: actions/checkout@v3

      - name: install package
        run: |
          pip install . 
          python foxglove-base-msgs/utils/generate_msgs.py  

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.3

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  
