name: Python package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_wheel:
    name: build wheel
    runs-on: macos-12
            
    steps:
      - name: install protobuf
        run: |
          brew install protobuf
      
      - uses: actions/checkout@v4

      - name: generate msgs
        run: python foxglove_base_msgs/utils/generate_msgs.py  

      - name: build wheel
        run: pip wheel -w . .

      - uses: actions/upload-artifact@v4
        with:
          name: fbm-wheel
          path: ./foxglove_base_msgs-*-py3-none-any.whl
  
  build_sdist:
    name: build source distribution
    runs-on: macos-12

    steps:
      - name: install protobuf
        run: |
          brew install protobuf

      - uses: actions/checkout@v4

      - name: generate msgs
        run: python foxglove_base_msgs/utils/generate_msgs.py 

      - name: Build sdist
        run: pipx run build --sdist
      
      - uses: actions/upload-artifact@v4
        with:
          name: fbm-source
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheel, build_sdist]
    runs-on: macos-12
    steps:
      - run: mkdir out

      - uses: actions/download-artifact@v4
        with:
          name: fbm-source
          path: out
      
      - uses: actions/download-artifact@v4
        with:
          name: fbm-wheel
          path: out

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine  

      - name: Build and publish
        run: |
          twine upload --verbose --repository-url http://150.230.201.125/ --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} out/*
  
