name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_wheel:
    name: Build wheel
    runs-on: macos-12
            
    steps:
      - name: Install dependencies
        run: |
          brew install protobuf
      
      - uses: actions/checkout@v3

      - name: install package
        run: |
          pip install . 
          python foxglove-base-msgs/utils/generate_msgs.py  

      - name: Build wheels
        run: pip wheel -w . .

      - uses: actions/upload-artifact@v3
        with:
          name: my-whl-artifacts
          path: |
            $(find . -name "*.whl")
  
