name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_wheel:
    name: build wheel
    runs-on: macos-12
            
    steps:
      - name: install protobuf
        run: |
          brew install protobuf
      
      - uses: actions/checkout@v4

      - name: generate msgs
        run: python foxglove_base_msgs/utils/generate_msgs.py  

      - name: build wheel
        run: pip wheel -w . .

      - run: mkdir out

      - uses: actions/upload-artifact@v4
        with:
          name: fbm-artifact
          path: out/foxglove_base_msgs-0.1-py3-none-any.whl
  
  build_sdist:
    name: build source distribution
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist
      
      - run: mkdir out

      - uses: actions/upload-artifact@v4
        with:
          name: source-distribution
          path: out/*.tar.gz

  upload_pypi:
    needs: [build_wheel, build_sdist]
    runs-on: macos-12
    steps:
      - run: mkdir out

      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: out

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine  

      - name: Build and publish
        run: |
          twine upload --verbose --repository-url http://150.230.201.125/ --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} out/*
  
